version: '3'
services:
    ### Server
    nginx:
        container_name: com-nginx
        restart: always
        build:
            context: ./
            dockerfile: ${PWD}/server/docker/nginx.docker
        volumes:
            - ./server:/app
        depends_on:
            - php
            - mongo
        ports:
            - "9999:80"
    php:
        container_name: com-php
        restart: always
        build:
            context: ./
            dockerfile: ${PWD}/server/docker/php.docker
        volumes:
            - ./server:/app
        depends_on:
            - elasticsearch
    ### Database
    mongo:
        image: mongo:latest
        container_name: com-mongo
        restart: always
        volumes:
            - ./data/db/mongo:/data/db
        ports:
            - "27017:27017"
        environment:
            MONGODB_DB: 'com'
    ### Client
    react:
        container_name: com-node
        restart: always
        build:
            context: ./
            dockerfile: ${PWD}/client/docker/client.docker
        volumes:
            - ./client:/app
        expose:
            - 8080
        ports:
            - 8080:3000
    ### ElasticSearech
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./data/search:/usr/share/elasticsearch/data
        ports:
            - 9201:9200